### ISSUE TITLE
Test and improve OpenPGP.js definitions

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/types#1]
ref https://github.com/openpgpjs/openpgpjs/issues/561

**Comment by tomholub** [comment]
4.1.0 api changes
API changes:

>     Key.prototype.getRevocationCertificate is now async
>     SubKey.prototype.getExpirationTime is now async and takes primaryKey, [date] as parameters instead of just [date]
>     When parsing a key with an authorized revocation key subpacket, we now return an error in the (await openpgp.key.read/readArmored(key)).err array, but also still return the key in the .keys array. This is because we ignore valid third-party revocation signatures made by authorized keys, so the key might not be safe to use in some cases.

**Comment by tomholub** [comment]
4.0.0 High-Level API Changes

> 
>     openpgp.message.fromText(), fromBinary(), readArmored() and
>     read() now accept ReadableStreams as well as Node streams.
> 
>     The high-level encrypt, decrypt, sign and verify functions now
>     have an streaming parameter, to control whether the return value
>     contains a stream. It can take the values "web", "node" or false.
>     It defaults to the type of stream you passed in, if any.
> 
>     When streaming, the signatures returned by verify and decrypt have
>     a verified: Promise<Boolean> property instead of valid: Boolean. The
>     signature property is also a Promise in that case.
> 
>     openpgp.{message,key,signature,cleartext}.readArmored() and
>     openpgp.{message,key,signature}.read() are now asynchronous. For example, instead of writing
> 
>     let publicKey = openpgp.key.readArmored(publicKeyArmored).keys[0];
> 
>     write, in an async function:
> 
>     let publicKey = (await openpgp.key.readArmored(publicKeyArmored)).keys[0];
> 
>     openpgp.encrypt() and openpgp.sign() now take a message
>     parameter instead of data, dataType and filename. Use
>     openpgp.message.fromText(), openpgp.message.fromBinary() or
>     openpgp.cleartext.fromText() to create a message. Note that if you
>     previously used the date parameter, you should now additionally pass
>     it to fromText/fromBinary as well.
> 
>     After calling let keyring = new openpgp.Keyring(), you now have to
>     call await keyring.load() to read the keys from LocalStorage.
>

**Comment by seisvelas** [comment]
Ha, what are the odds. I Google'd "openpgp.crypto.hash.digest" and there were only three results - this issue is the second one.

The internet is small sometimes!
